---
model: final_mlp
dataset: criteo_x1
num_features: [I1, I2, I3, I4, I5, I6, I7, I8, I9, I10, I11, I12, I13]
cat_features: [C1, C2, C3, C4, C5, C6, C7, C8, C9, C10, C11, C12, C13, C14, C15, C16, C17, C18, C19, C20, C21, C22, C23, C24, C25, C26]
data_dir: data/Criteo_x1
max_train_rows: null
verbose: false
deterministic: true

model_params:
  random_state: 2021
  loss: bce
  embedding_dim: 10
  num_encoder: "linear:embedding_dim=10"
  cat_encoder: per_feature
  normalize_numeric: false
  numeric_nan_fill: zero
  mlp1_hidden_units: [400, 400, 400]
  mlp1_hidden_activations: relu
  mlp1_dropout: 0.2
  mlp1_batch_norm: true
  mlp2_hidden_units: [1000]
  mlp2_hidden_activations: relu
  mlp2_dropout: 0.3
  mlp2_batch_norm: true
  use_fs: true
  fs_hidden_units: [800]
  fs1_context: [I1, I2, I3, I4, I5, I6, I7, I8, I9, I10, I11, I12, I13]
  fs2_context: [C6]
  num_heads: 200
  lr: 1.0e-3
  optimizer: adamw
  optimizer_kwargs:
    adam_beta1: 0.9
    adam_beta2: 0.999
    adam_eps: 1.0e-8
    amsgrad: false
  weight_decay: 0.0
  embedding_regularizer: 1.0e-5
  lr_scheduler: "plateau:patience=0;factor=0.1;min_lr=1e-6"
  epochs: 100
  batch_size: 4096
  early_stopping_rounds: 2
  eval_metric: auc
  chunk_rows: 50000000
