model: destine
dataset: criteo_x1
num_features:
- I1
- I2
- I3
- I4
- I5
- I6
- I7
- I8
- I9
- I10
- I11
- I12
- I13
cat_features:
- C1
- C2
- C3
- C4
- C5
- C6
- C7
- C8
- C9
- C10
- C11
- C12
- C13
- C14
- C15
- C16
- C17
- C18
- C19
- C20
- C21
- C22
- C23
- C24
- C25
- C26
data_dir: data/Criteo_x1
max_train_rows: null
verbose: false
deterministic: true
model_params:
  random_state: 2021
  loss: bce
  embedding_dim: 32
  attention_dim: 64
  num_heads: 2
  attention_layers: 5
  residual_mode: last_layer
  attention_dropout: 0.2
  attention_activation: true
  scale_attention: false
  unary_mode: paper
  use_wide: true
  dnn_hidden_units:
  - 400
  - 400
  normalize_numeric: true
  numeric_nan_fill: median
  lr: 0.0005
  weight_decay: 5.0e-06
  grad_clip_norm: null
  lr_scheduler: null
  epochs: 100
  batch_size: 10000
  early_stopping_rounds: 2
  eval_metric: auc
  chunk_rows: 50000000
  net_dropout: 0.2
  batch_norm: true
  optimizer: adam
